if (getRversion() >= "2.15.1") {
  utils::globalVariables(c("constraint_name",
                           "allowed",
                           "fl_area",
                           "min_setback",
                           "max_setback",
                           "geometry",
                           "side",
                           "parcel_id",
                           "lot_width",
                           "lot_depth",
                           "lot_area",
                           "lot_type",
                           "zoning_data",
                           "overlay",
                           "planned_dev",
                           "pd_id",
                           "false_reasons",
                           "check_pd",
                           "maybe_reasons",
                           "overlay_id",
                           "has_false",
                           "has_maybe",
                           "reason",
                           "possible_checks",
                           "zoning_id",
                           "district_check",
                           "muni_name",
                           "num_allowed",
                           "num_maybe",
                           "num_prohib",
                           "Freq",
                           "reasons",
                           "Var1",
                           "Reason for prohibition",
                           "Number of parcels",
                           "Reason for ambiguity",
                           "dist_abbr",
                           "allowed_now",
                           "bldg_fit",
                           "has_overlay",
                           "overlay_type"))
}
